name: approve

on: pull_request # run on pull request

permissions:
  pull-requests: write # grant write permissions on the pull request endpoint

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - run: | # approve the pull request
        curl --request POST \
        --url https://api.github.com/repos/${{github.repository}}/pulls/${{github.event.number}}/reviews \
        --header 'authorization: Bearer ${{secrets.GITHUB_TOKEN}}' \
        --header 'content-type: application/json' \
        -d '{"event":"APPROVE"}'
